"""Cleaned up relationships between posts/projects and photos, added deleting photos independently

Revision ID: 522be99fa883
Revises: 2f6741bf87c7
Create Date: 2025-05-02 07:06:55.857733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522be99fa883'
down_revision = '2f6741bf87c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('photo', schema=None) as batch_op:
        #batch_op.create_unique_constraint(batch_op.f('uq_photo_filename'), ['filename'])

    #with op.batch_alter_table('post', schema=None) as batch_op:
        #batch_op.create_foreign_key(batch_op.f('fk_post_image_filename_photo'), 'photo', ['image_filename'], ['filename'], ondelete='SET NULL')

    #with op.batch_alter_table('project', schema=None) as batch_op:
       # batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
       # batch_op.create_index(batch_op.f('ix_project_date_posted'), ['date_posted'], unique=False)
       # batch_op.create_foreign_key(batch_op.f('fk_project_image_filename_photo'), 'photo', ['image_filename'], ['filename'], ondelete='SET NULL')

    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # with op.batch_alter_table('project', schema=None) as batch_op:
   #     batch_op.drop_constraint(batch_op.f('fk_project_image_filename_photo'), type_='foreignkey')
   #     batch_op.drop_index(batch_op.f('ix_project_date_posted'))
   #     batch_op.drop_column('date_posted')

   # with op.batch_alter_table('post', schema=None) as batch_op:
   #     batch_op.drop_constraint(batch_op.f('fk_post_image_filename_photo'), type_='foreignkey')

   # with op.batch_alter_table('photo', schema=None) as batch_op:
    #    batch_op.drop_constraint(batch_op.f('uq_photo_filename'), type_='unique')

    # ### end Alembic commands ###
    pass