"""Updated models with Post polymorphism and photo_id FKs

Revision ID: 760a603f8a4a
Revises: 522be99fa883
Create Date: 2025-05-22 02:06:14.311775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760a603f8a4a'
down_revision = '522be99fa883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos')),
    sa.UniqueConstraint('filename', name=op.f('uq_photos_filename'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_link', sa.String(length=256), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='fk_projects_photo_id_photos', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_photo_id'), ['photo_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_link', sa.String(length=256), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='fk_posts_photo_id_photos', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_posts_project_id_projects', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_type'), ['type'], unique=False)

    op.create_table('music_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('artist', sa.String(length=120), nullable=True),
    sa.Column('album_title', sa.String(length=256), nullable=True),
    sa.Column('spotify_link', sa.String(length=256), nullable=True),
    sa.Column('youtube_link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['posts.id'], name='fk_music_items_id_posts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music_items'))
    )
    with op.batch_alter_table('music_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_items_item_type'), ['item_type'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=256), nullable=True),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.Column('director_author', sa.String(length=120), nullable=True),
    sa.Column('item_link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['posts.id'], name='fk_reviews_id_posts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_category'), ['category'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['posts.id'], name='fk_videos_id_posts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_source_type'), ['source_type'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_date_posted')
        batch_op.drop_index('ix_post_project_id')

    op.drop_table('post')
    op.drop_table('photo')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_date_posted')

    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=120), nullable=True),
    sa.Column('github_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['image_filename'], ['photo.filename'], name='fk_project_image_filename_photo', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_project')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('ix_project_date_posted', ['date_posted'], unique=False)

    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=510), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_photo'),
    sa.UniqueConstraint('filename', name='uq_photo_filename')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('image_filename', sa.VARCHAR(length=120), nullable=True),
    sa.Column('github_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['image_filename'], ['photo.filename'], name='fk_post_image_filename_photo', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='fk_post_project'),
    sa.PrimaryKeyConstraint('id', name='pk_post')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_post_date_posted', ['date_posted'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_source_type'))

    op.drop_table('videos')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_category'))

    op.drop_table('reviews')
    with op.batch_alter_table('music_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_items_item_type'))

    op.drop_table('music_items')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_type'))
        batch_op.drop_index(batch_op.f('ix_posts_project_id'))
        batch_op.drop_index(batch_op.f('ix_posts_date_posted'))

    op.drop_table('posts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_photo_id'))
        batch_op.drop_index(batch_op.f('ix_projects_date_posted'))

    op.drop_table('projects')
    op.drop_table('photos')
    # ### end Alembic commands ###
