"""added featured_project field to Project Model

Revision ID: 9432fd36c2a5
Revises: 760a603f8a4a
Create Date: 2025-08-29 07:37:26.413053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9432fd36c2a5'
down_revision = '760a603f8a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_is_featured'), ['is_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_is_featured'))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
