"""Add post_images and project_images gallery tables

Revision ID: b7e3c9a1d4f2
Revises: a10392e21601
Create Date: 2026-06-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e3c9a1d4f2'
down_revision = 'a10392e21601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('photo_id', sa.Integer(), nullable=False),
        sa.Column('placeholder_key', sa.String(length=16), nullable=False),
        sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('caption', sa.String(length=512), nullable=True),
        sa.Column('alt_text', sa.String(length=512), nullable=True),
        sa.Column('alignment', sa.String(length=10), server_default=sa.text("'center'"), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_images_post_id_posts'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_post_images_photo_id_photos'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_post_images')),
        sa.UniqueConstraint('post_id', 'placeholder_key', name=op.f('uq_post_images_post_key')),
        sa.CheckConstraint("alignment IN ('left', 'right', 'center', 'full')", name=op.f('ck_post_images_alignment')),
    )
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_images_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_images_post_id_position'), ['post_id', 'position'], unique=False)

    op.create_table(
        'project_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('photo_id', sa.Integer(), nullable=False),
        sa.Column('placeholder_key', sa.String(length=16), nullable=False),
        sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('caption', sa.String(length=512), nullable=True),
        sa.Column('alt_text', sa.String(length=512), nullable=True),
        sa.Column('alignment', sa.String(length=10), server_default=sa.text("'center'"), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_images_project_id_projects'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_project_images_photo_id_photos'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_project_images')),
        sa.UniqueConstraint('project_id', 'placeholder_key', name=op.f('uq_project_images_project_key')),
        sa.CheckConstraint("alignment IN ('left', 'right', 'center', 'full')", name=op.f('ck_project_images_alignment')),
    )
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_images_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_images_project_id_position'), ['project_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_images_project_id_position'))
        batch_op.drop_index(batch_op.f('ix_project_images_photo_id'))
    op.drop_table('project_images')

    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_images_post_id_position'))
        batch_op.drop_index(batch_op.f('ix_post_images_photo_id'))
    op.drop_table('post_images')
    # ### end Alembic commands ###
